### ISSUE TITLE
Where is the financial order book data?

### ISSUE THREAD

**Issue by dmzou** [achab/nphc#1]
In /examples/order_book_data.ipynb
`store = pd.HDFStore('/data/data/QH/L1.h5', 'r')
`
where is L1.h5?
Thanks in advance.

**Comment by achab** [comment]
The data has been provided by QuantHouse and I can't unfortunately share it. See section 4.1 of [this article](https://arxiv.org/pdf/1706.03411.pdf) to have a description of the dataset.
