### ISSUE TITLE
Setting parameter H

### ISSUE THREAD

**Issue by DemenzEchtbaer** [achab/nphc#2]
Dear Dr. Achab,

Thank you very much for bringing us NPHC! 
You mention, in "Analysis of order book flows using a non-parametric estimation of the branching ratio matrix" (Quantitative Finance, 18(2):199–212.), a procedure to set parameter H (page 4): 
1. compute estimates of the covariance density at several points.
2. assess the characteristic time τ after which the covariance density is
negligible.
3. setting H to a multiple of this time for instance H = 5 x τ.
I do have a couple questions regarding this method, namely:
- Do you try to come as close as possible to the critical point when choosing a multiple of τ?
- In a case when even 1 x τ leads to a spectral radius > 1, does this mean there was an error in computing τ or can we set H to a fraction of τ, for example H = 1/2 τ?
- Would you willing, by any chance, to share the code you used to set H in the aforementioned paper? 
Thanks in advance.

**Comment by achab** [comment]
Dear @DemenzEchtbaer,

Here are my answers:
1) Typically, covariance density decreases as a power law function ie as 1 / \alpha. After estimating the covariance density or the integrated covariance, you can guess alpha and basically select \tau such that the integral between - \tau and \tau equals 0.9 times the whose integral.
2) Playing with real data, this can indeed happen. You should then select a window size H for which you believe all interesting information will be included. Note that taking a size H too high may introduce some noise. The method is not supposed to work in this regime but still gives interpretable results.
3) I know longer have this part of the code. You can reuse the computation of C, [here](https://github.com/achab/nphc/blob/master/nphc/cumulants.py#L97), and select H given the criteria stated above.

Hope this helps !

Massil Achab

**Comment by DemenzEchtbaer** [comment]
Dear Dr. Achab,

This definitely helps! Thank you again for your insights!

Best,
