### ISSUE TITLE
Prediction with NPHC

### ISSUE THREAD

**Issue by csaiedu** [achab/nphc#4]
Hi,

How does one predicts with the NPHC process? 

Thanks

**Comment by achab** [comment]
Hello,

We can't, it's not the goal of the method. This methods aims at giving a causality map of historical data.

**Comment by csaiedu** [comment]
Thanks Sent from Mail for Windows From: massilSent: Monday 15 November 2021 12:11To: achab/nphcCc: csaiedu; AuthorSubject: Re: [achab/nphc] Prediction with NPHC (Issue #4) Hello,We can't, it's not the goal of the method. This methods aims at giving a causality map of historical data.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android.
